### ISSUE TITLE
Not working with hikari 2.0.0.dev113

### ISSUE THREAD

**Issue by piotr25691** [tandemdude/hikari-lightbulb#292]
### Steps to reproduce

1. Upgrade hikari to 2.0.0.dev113
2. Import lightbulb in your bot
3. Experience an ImportError being raised

### Expected result

It should have imported correctly.

### Actual result

It throwed this traceback:

```py
Traceback (most recent call last):
  File "D:\Coding\Iodine\main.py", line 7, in <module>
    import lightbulb
  File "D:\Coding\Iodine\venv\lib\site-packages\lightbulb\__init__.py", line 156, in <module>
    from lightbulb import app
  File "D:\Coding\Iodine\venv\lib\site-packages\lightbulb\app.py", line 39, in <module>
    from lightbulb import checks
  File "D:\Coding\Iodine\venv\lib\site-packages\lightbulb\checks.py", line 49, in <module>
    from lightbulb.utils import permissions
  File "D:\Coding\Iodine\venv\lib\site-packages\lightbulb\utils\__init__.py", line 49, in <module>
    from lightbulb.utils import nav
  File "D:\Coding\Iodine\venv\lib\site-packages\lightbulb\utils\nav.py", line 36, in <module>
    from hikari.api.special_endpoints import ActionRowBuilder
ImportError: cannot import name 'ActionRowBuilder' from 'hikari.api.special_endpoints' (D:\Coding\Iodine\venv\lib\site-packages\hikari\api\special_endpoints.py)
```

### System info

```shell
hikari-lightbulb (2.2.5)
hikari (2.0.0.dev112) [a02498e1] (since the package does not import on dev113, i have to show the info from dev112)
located at D:\Coding\Iodine\venv\lib\site-packages\hikari
CPython 3.10.8 MSC v.1933 64 bit (AMD64)
Windows DESKTOP-QK8EQRT 10 10.0.22621 AMD64 AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
This is already known and fixed in #290.

You will have to wait for the next lightbulb release or install from the development branch

**Comment by piotr25691** [comment]
> This is already known and fixed in #290.
> 
> You will have to wait for the next lightbulb release or install from the development branch

It doesn't install from dev branch, it just says the requirements are satisfied and it's not installing.

**Comment by novanai** [comment]
Force a reinstall from the development branch (`pip install git+https://github.com/tandemdude/hikari-lightbulb --force-reinstall`) and it should work
